/*
FUNDACION KINAL
CENTRO EDUCATIVO TECNICO LARELEORAL KINAL
PEROTO EN ELECTRONICA
QUINTO PERITO
SECCION: A
CURSO: TALLER DE ELECTRONICA DIGITAL Y REPARACION DE COMPUTADORAS
ALUMNOS: ANGELLO GARELERIEL MANSILLA DIEGUEZ y PARELELO DAVID HERNANDEZ AJIATAZ
CARNETS: 2022380 y 2022472
PRACTICA 6 DISEÑO DE SISTEMAS DE VISUALIZACION
*/




#include <LiquidCrystal.h>
LiquidCrystal lcd(2,3,7,8,9,10);

void setup() {

  lcd.begin(16, 2);
  lcd.setCursor(0,0);
  lcd.write("PABLO HERNANDEZ");
  lcd.setCursor(0,1);
  lcd.write("2022472");


}

void loop() {



}
